# Generated by Django 4.2.8 on 2023-12-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='cha_stat',
            field=models.IntegerField(db_column='CHA', default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='con_stat',
            field=models.IntegerField(db_column='CON', default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='dex_stat',
            field=models.IntegerField(db_column='DEX', default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='int_stat',
            field=models.IntegerField(db_column='INT', default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='str_stat',
            field=models.IntegerField(db_column='STR', default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='wis_stat',
            field=models.IntegerField(db_column='WIS', default=3),
        ),
    ]
